using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class WorkerAnt : MonoBehaviour {

	public int carrying;			//the amount of food the ant is carrying
	public int carryingThreshold;	//the threshold above which the ant will return to the nest

	// Use this for initialization
	void Start () 
	{
		
	}
	
	// Update is called once per frame
	void Update () 
	{
		//transform.Translate (Vector3.forward * Time.deltaTime);
	}

	//determines if the nat can carry food or not
	void CanCarry()
	{

	}

	//navigates towards nest and drops food there
	void DepositFood()
	{

	}

	//drops food
	void DropFood()
	{

	}

	//determines the best use of the food e.g. carry or eat
	void UseFood()
	{

	}

	//performs the action required Touch complete the current goal
	void DoTask()
	{

	}

	//deteremines the current goal of the ant
	void UpdateGoal()
	{

	}

	//updates the ants health
	void UpdateHealth()
	{

	}
}
